'use strict';
const $=id=>document.getElementById(id), KEY='bag-charm-studio-v1';
const positions=[[43,39],[69,43],[43,72],[70,74]];
let state={round:0,bag:null,slots:[null,null,null,null],designs:[]}, selected=null;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Number.isInteger(s.round)&&s.round>=0&&s.round<10&&Array.isArray(s.slots)&&s.slots.length===4&&s.slots.every(x=>x===null||Object.hasOwn(ITEMS,x))&&new Set(s.slots.filter(Boolean)).size===s.slots.filter(Boolean).length&&(s.bag===null||BAGS.includes(s.bag))&&Array.isArray(s.designs)&&s.designs.length===s.round&&s.designs.every((d,i)=>d&&Array.isArray(d.slots)&&assess(ROUNDS[i],d.bag,d.slots).complete))state=s;}catch{}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}}
function asset(kind,id){return `assets/${kind}-${id}.webp`;}
function label(id){return id[0].toUpperCase()+id.slice(1);}
function renderItems(){const q=$('search').value.trim().toLowerCase();$('items').replaceChildren();for(const [id,name]of Object.entries(ITEMS)){if(!name.toLowerCase().includes(q))continue;const b=document.createElement('button');b.className='item'+(selected===id?' selected':'')+(state.slots.includes(id)?' used':'');b.dataset.item=id;b.draggable=true;b.setAttribute('aria-pressed',selected===id);b.setAttribute('aria-label',name+(state.slots.includes(id)?', attached':''));b.innerHTML=`<img src="${asset('item',id)}" alt="" draggable="false"><span>${name}</span>`;b.onclick=()=>{if(!state.bag){announce('Choose a backpack before adding pieces.');return;}selected=selected===id?null:id;renderItems();$('instruction').textContent=selected?`${name} selected. Tap a spot to place it.`:'Pick a piece, then tap a spot.';};b.ondragstart=e=>{e.dataTransfer.setData('text/plain',id);e.dataTransfer.effectAllowed='copy';};$('items').append(b);}if(!$('items').children.length){const p=document.createElement('p');p.textContent='No matching pieces.';p.style.fontSize='12px';$('items').append(p);}}
function renderBags(){for(const id of BAGS){const b=document.createElement('button');b.className='bag-option';b.dataset.bag=id;b.innerHTML=`<img src="${asset('bag',id)}" alt=""><span>${label(id)}</span>`;b.setAttribute('aria-label',`${label(id)} backpack`);b.onclick=()=>{state.bag=id;save();renderDesign();};$('bags').append(b);}}
function announce(msg){$('feedback').textContent=msg;}
function place(i,id){if(!state.bag){announce('Choose a backpack first.');return;}if(!Object.hasOwn(ITEMS,id))return;const old=state.slots.indexOf(id);if(old!==-1)state.slots[old]=null;state.slots[i]=id;selected=null;save();renderDesign();renderItems();}
function check(){const result=assess(ROUNDS[state.round],state.bag,state.slots);$('next').hidden=!result.complete;$('next').textContent=state.round===9?'See all ten designs →':'Next customer →';const n=state.slots.filter(Boolean).length;$('count').textContent=`${n} / 4 pieces`;if(result.complete){announce(`Perfect match! ${ROUNDS[state.round].name} will love this bag.`);return;}if(!state.bag){announce('Find the colour and four interests in the story.');return;}if(n===4){announce(`${result.bag?'The bag colour matches.':'Check the bag colour in the story.'} ${result.correct} of 4 pieces match. Select a new piece, then tap one to replace it.`);}else{announce(`${result.bag?'Bag colour matched!':'Look again at the colour clue.'} Add ${4-n} more ${4-n===1?'piece':'pieces'}.`);}}
function renderDesign(){const img=$('main-bag');img.hidden=!state.bag;$('empty-bag').hidden=!!state.bag;if(state.bag){img.src=asset('bag',state.bag);img.alt=`${label(state.bag)} backpack for ${ROUNDS[state.round].name}`;}document.querySelectorAll('.bag-option').forEach(b=>{b.classList.toggle('selected',b.dataset.bag===state.bag);b.setAttribute('aria-pressed',b.dataset.bag===state.bag);});$('spots').replaceChildren();if(state.bag)positions.forEach(([x,y],i)=>{const id=state.slots[i],b=document.createElement('button');b.className='spot'+(id?' filled':'');b.style.left=x+'%';b.style.top=y+'%';b.dataset.spot=i;b.setAttribute('aria-label',id?`Spot ${i+1}: ${ITEMS[id]}. Activate to remove or replace.`:`Empty spot ${i+1}`);b.innerHTML=id?`<img src="${asset('item',id)}" alt=""><span class="remove" aria-hidden="true">×</span>`:'+';b.onclick=()=>{if(selected)place(i,selected);else if(id){state.slots[i]=null;save();renderDesign();renderItems();}else announce('Choose a piece from the collection, then tap this spot.');};b.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';};b.ondrop=e=>{e.preventDefault();place(i,e.dataTransfer.getData('text/plain'));};$('spots').append(b);});$('instruction').textContent=state.bag?'Pick a piece, then tap a spot. Tap an attached piece to remove it.':'Choose a backpack from the right.';check();}
function renderRound(){const r=ROUNDS[state.round];selected=null;$('search').value='';$('progress').textContent=`Customer ${state.round+1} / 10`;$('work-title').textContent=`Make it ${r.name}’s`;$('portrait').src=asset('person',r.id);$('portrait').alt=r.name;$('person-name').textContent=r.name;$('story-text').textContent=r.story;renderDesign();renderItems();$('items').scrollTop=0;}
function finish(){const designs=[...state.designs,{bag:state.bag,slots:[...state.slots]}];$('gallery').replaceChildren();designs.forEach((d,i)=>{const card=document.createElement('div');card.className='gallery-card';card.innerHTML=`<div class="mini-design"><img src="${asset('bag',d.bag)}" alt="${ROUNDS[i].name}'s ${d.bag} backpack">${d.slots.map((id,j)=>`<img class="mini-piece" src="${asset('item',id)}" alt="${ITEMS[id]}" style="left:${positions[j][0]}%;top:${positions[j][1]}%">`).join('')}</div><span>${ROUNDS[i].name}</span>`;$('gallery').append(card);});$('finish').showModal();}
$('next').onclick=()=>{if(!assess(ROUNDS[state.round],state.bag,state.slots).complete)return;if(state.round===9){finish();return;}state.designs.push({bag:state.bag,slots:[...state.slots]});state.round++;state.bag=null;state.slots=[null,null,null,null];save();renderRound();$('work-title').tabIndex=-1;$('work-title').focus();};
function reset(){state={round:0,bag:null,slots:[null,null,null,null],designs:[]};save();renderRound();}
$('search').oninput=renderItems;$('restart').onclick=()=>$('restart-dialog').showModal();$('cancel-restart').onclick=()=>$('restart-dialog').close();$('confirm-restart').onclick=()=>{$('restart-dialog').close();reset();};$('play-again').onclick=()=>{$('finish').close();reset();};renderBags();renderRound();
// Keep attachment coordinates aligned with the square artwork at every size.
const stage=document.querySelector('.bag-stage');
new ResizeObserver(()=>{const size=Math.min(stage.clientWidth,stage.clientHeight);$('bag-canvas').style.width=size+'px';$('bag-canvas').style.height=size+'px';}).observe(stage);
