const BAGS = ['pink','blue','mint','lavender','yellow','orange','red','cream','navy'];
const ITEMS = {chess:'Chess',baking:'Baking',gardening:'Gardening',ballet:'Ballet',astronomy:'Telescope',coding:'Coding',sewing:'Sewing',camping:'Camping',karate:'Karate',origami:'Origami','mini-backpack':'Mini backpack',wand:'Magic wand',mermaid:'Mermaid tail',microphone:'Microphone',science:'Science flask',robot:'Robot',butterfly:'Butterfly',donut:'Donut',treasure:'Treasure chest',axolotl:'Axolotl',skateboard:'Skateboard',cat:'Cat',unicorn:'Unicorn',slime:'Slime',cupcake:'Cupcake',tennis:'Tennis',rainbow:'Rainbow',rocket:'Rocket',panda:'Panda',puzzle:'Puzzle','bubble-tea':'Bubble tea',gaming:'Gaming','roller-skate':'Roller skate',dinosaur:'Dinosaur',camera:'Camera',art:'Art palette',planet:'Planet',book:'Book',headphones:'Headphones',football:'Football'};
const ROUNDS = [
{id:'mia',name:'Mia',bag:'pink',items:['ballet','wand','unicorn','rainbow'],story:"Hello! I'm Mia. I like pink. I have dance lessons on Mondays. I like magic stories. My favourite animal is a white horse with a horn. I love the colours in the sky after rain."},
{id:'mei',name:'Mei',bag:'mint',items:['gardening','origami','panda','bubble-tea'],story:"Hi! I'm Mei. I like light green. I water my flowers every day. On Fridays, I make birds from paper. My favourite animal is black and white. It eats bamboo. I like tea with little balls in it."},
{id:'ruby',name:'Ruby',bag:'red',items:['microphone','headphones','gaming','roller-skate'],story:"Hello! I'm Ruby. I like red. I sing at school on Mondays. I listen to music on the bus, just for me! I play video games on Fridays. I like shoes with wheels. I wear them in the park."},
{id:'ella',name:'Ella',bag:'blue',items:['mermaid','axolotl','treasure','camera'],story:"Hi! I'm Ella. I like light blue. I love stories about girls with fish tails. They look for boxes of gold! My pet is an axolotl. It lives in water. On Sundays, I take photos of my family."},
{id:'zoe',name:'Zoe',bag:'yellow',items:['karate','football','tennis','skateboard'],story:"Hello! I'm Zoe. I like yellow. I do karate on Tuesdays. I play football after school. On Mondays and Fridays, I play tennis. On Saturdays, I ride a board with four wheels in the park."},
{id:'sophie',name:'Sophie',bag:'cream',items:['baking','cupcake','donut','sewing'],story:"Hi! I'm Sophie. I like cream, a very light yellow. I make cakes with Mum on Sundays. I love little cakes in paper cups. I also like sweet rings from the cake shop. I make clothes for my dolls, too."},
{id:'luna',name:'Luna',bag:'lavender',items:['astronomy','planet','rocket','book'],story:"Hello! I'm Luna. I like light purple. At night, I look at stars. They are far away, so I use a special tube. I like the planet with rings. I want to fly into space! I read every evening."},
{id:'isla',name:'Isla',bag:'navy',items:['coding','robot','science','slime'],story:"Hi! I'm Isla. I like dark blue. I make games on my computer. I build little robots on Saturdays. I mix colourful liquids in science class. At home, I play with soft, sticky slime."},
{id:'freya',name:'Freya',bag:'orange',items:['camping','butterfly','dinosaur','mini-backpack'],story:"Hello! I'm Freya. I like orange. I sleep in a tent on holiday. I like little insects with big, colourful wings. I love big animals from long ago. I also collect very small bags. They are too small for my books!"},
{id:'maya',name:'Maya',bag:'pink',items:['chess','puzzle','cat','art'],story:"Hi! I'm Maya. I like pink. I play a game with kings and queens. I put little pieces together to make a picture. I have a pet. It says 'meow'! On Tuesdays, I have art lessons. I love to paint."}
];
function assess(round,bag,slots){return {bag:bag===round.bag,correct:slots.filter(x=>round.items.includes(x)).length,complete:bag===round.bag&&slots.length===4&&new Set(slots).size===4&&round.items.every(x=>slots.includes(x))};}
