const BAGS = ['pink','blue','mint','lavender','yellow','orange','red','cream','navy'];
const ITEMS = {chess:'Chess',baking:'Baking',gardening:'Gardening',ballet:'Ballet',astronomy:'Telescope',coding:'Coding',sewing:'Sewing',camping:'Camping',karate:'Karate',origami:'Origami','mini-backpack':'Mini backpack',wand:'Magic wand',mermaid:'Mermaid tail',microphone:'Microphone',science:'Science flask',robot:'Robot',butterfly:'Butterfly',donut:'Donut',treasure:'Treasure chest',axolotl:'Axolotl',skateboard:'Skateboard',cat:'Cat',unicorn:'Unicorn',slime:'Slime',cupcake:'Cupcake',tennis:'Tennis',rainbow:'Rainbow',rocket:'Rocket',panda:'Panda',puzzle:'Puzzle','bubble-tea':'Bubble tea',gaming:'Gaming','roller-skate':'Roller skate',dinosaur:'Dinosaur',camera:'Camera',art:'Art palette',planet:'Planet',book:'Book',headphones:'Headphones',football:'Football'};
const ROUNDS = [
{id:'mia',name:'Mia',bag:'pink',items:['ballet','wand','unicorn','rainbow'],story:'Mia wants a pink backpack for her after-school adventures. She practises ballet, invents spells with a magic wand, and fills her sketchbook with unicorns beneath rainbows.'},
{id:'mei',name:'Mei',bag:'mint',items:['gardening','origami','panda','bubble-tea'],story:'Mei would love a mint-green backpack. She grows flowers on her balcony and folds paper cranes. Pandas are her favourite animals, and she orders bubble tea as a weekend treat.'},
{id:'ruby',name:'Ruby',bag:'red',items:['microphone','headphones','gaming','roller-skate'],story:'Ruby has her heart set on a red backpack. She sings into a microphone at school concerts and listens to music through headphones. After homework, she plays video games or goes roller skating.'},
{id:'ella',name:'Ella',bag:'blue',items:['mermaid','axolotl','treasure','camera'],story:'Ella wants a sky-blue backpack, as light as a clear summer sky. She writes stories about mermaids finding treasure chests. She cares for a pet axolotl and takes photos with her camera.'},
{id:'zoe',name:'Zoe',bag:'yellow',items:['karate','football','tennis','skateboard'],story:'Zoe chooses sunny yellow for her new backpack. She wears a white uniform to karate, plays football with her friends, and practises tennis serves. On Saturdays, she rides her skateboard.'},
{id:'sophie',name:'Sophie',bag:'cream',items:['baking','cupcake','donut','sewing'],story:'Sophie is looking for a cream-coloured drawstring backpack. She loves mixing cake batter, decorating cupcakes, and sharing donuts. She also uses a needle and thread to sew little gifts.'},
{id:'luna',name:'Luna',bag:'lavender',items:['astronomy','planet','rocket','book'],story:'Luna wants a lavender backpack. She looks at the night sky through a telescope and reads books about space. Her bedroom has models of a ringed planet and a rocket ready to launch.'},
{id:'isla',name:'Isla',bag:'navy',items:['coding','robot','science','slime'],story:'Isla needs a dark navy-blue backpack. She writes computer code and builds small robots. In science club, she experiments with colourful liquids in flasks and makes stretchy slime.'},
{id:'freya',name:'Freya',bag:'orange',items:['camping','butterfly','dinosaur','mini-backpack'],story:'Freya wants an orange backpack for her next trip. She camps in a tent and watches butterflies on woodland walks. She collects dinosaur models and tiny backpack-shaped keyrings.'},
{id:'maya',name:'Maya',bag:'pink',items:['chess','puzzle','cat','art'],story:'Maya would like a pink backpack. She plays chess and solves jigsaw puzzles on rainy days. She adores cats and uses a palette and brushes to paint their portraits.'}
];
function assess(round,bag,slots){return {bag:bag===round.bag,correct:slots.filter(x=>round.items.includes(x)).length,complete:bag===round.bag&&slots.length===4&&new Set(slots).size===4&&round.items.every(x=>slots.includes(x))};}
